app.controller('classifyController',['$scope',function($scope){
	$scope.classifyImgText=[
		{
			url:'/images/dengshi.png',
			text:'灯饰',
			jump:'dengshi',
			isTrue:false
		},
		{
			url:'/images/shizhong.png',
			text:'时钟',
			jump:'shizhong',
			isTrue:false
		},
		{
			url:'/images/riyong.png',
			text:'日用',
			jump:'riyong',
			isTrue:false
		},
		{
			url:'/images/canyin.png',
			text:'餐饮',
			jump:'canyin',
			isTrue:false
		},
		{
			url:'/images/zhuangshi.png',
			text:'装饰',
			jump:'zhuangshi',
			isTrue:false
		},
		{
			url:'/images/yizhi.png',
			text:'益智',
			jump:'yizhi',
			isTrue:false
		},
		{
			url:'/images/shouna.png',
			text:'收纳',
			jump:'shouna',
			isTrue:false
		},
		{
			url:'/images/fenlei@2x.png',
			text:'分类',
			jump:'fenlei',
			isTrue:false
		}		
	];

	
 
}])
