app.controller('homeController',['$scope', '$ionicSlideBoxDelegate',function($scope, $ionicSlideBoxDelegate){
	$scope.bannerImgUrl=[
		'/images/banner1.png',
		'/images/banner2.jpg',
		'/images/banner3.jpg',
		'/images/banner1.png',
		'/images/banner2.jpg',
	]
	$scope.items=[
		{
			url:'/images/dengshi.png',
			text:'灯饰',
			jump:'dengshi'
		},
		{
			url:'/images/shizhong.png',
			text:'时钟',
			jump:'shizhong'

		},
		{
			url:'/images/riyong.png',
			text:'日用',
			jump:'riyong'
		},
		{
			url:'/images/canyin.png',
			text:'餐饮',
			jump:'canyin'
		},
		{
			url:'/images/zhuangshi.png',
			text:'装饰',
			jump:'zhuangshi'
		},
		{
			url:'/images/yizhi.png',
			text:'益智',
			jump:'yizhi'
		},
		{
			url:'/images/shouna.png',
			text:'收纳',
			jump:'shouna'
		},
		{
			url:'/images/fenlei@2x.png',
			text:'分类',
			jump:'fenlei'
		}
	]
	$ionicSlideBoxDelegate.update();
	$ionicSlideBoxDelegate.loop(true);
}])
